import requests
from API.admin_panel_filters.test_000_save_token import SaveToken
from API.admin_panel_filters.test_002_filter_homework_tab_home_school import TestFilterGradesInHomework
from API.admin_panel_filters.test_002_filter_homework_tab_home_school import TestFilterSubjectsInHomework
from API.admin_panel_filters.test_002_filter_homework_tab_home_school import TestFilterTypeDz
from API.admin_panel_filters.test_002_filter_homework_tab_home_school import TestFilterStatusDz
from API.admin_panel_filters.test_002_filter_homework_tab_home_school import TestFilterFormatAccess
from API.admin_panel_filters.test_001_filter_assessments_journal_tab_home_school import TestFilterQuarter
from API.admin_panel_filters.test_001_filter_assessments_journal_tab_home_school import TestFilterYears
from API.admin_panel_filters.test_001_filter_assessments_journal_tab_home_school import TestTrainingFormat
from API.admin_panel_filters.test_001_filter_assessments_journal_tab_home_school import TestFilterSchool
from API.admin_panel_filters.test_001_filter_assessments_journal_tab_home_school import TestFilterSubjectsInAssessmentsJournal
from API.admin_panel_filters.test_001_filter_assessments_journal_tab_home_school import TestFilterGradesInAssessmentsJournal
from API.admin_panel_filters.test_001_filter_assessments_journal_tab_home_school import TestFilterUser

suite = requests.TestSuite()

suite.addTest(requests.makeSuite(SaveToken))
suite.addTest(requests.makeSuite(TestFilterGradesInHomework))
suite.addTest(requests.makeSuite(TestFilterSubjectsInHomework))
suite.addTest(requests.makeSuite(TestFilterTypeDz))
suite.addTest(requests.makeSuite(TestFilterStatusDz))
suite.addTest(requests.makeSuite(TestFilterFormatAccess))
suite.addTest(requests.makeSuite(TestFilterQuarter))
suite.addTest(requests.makeSuite(TestFilterYears))
suite.addTest(requests.makeSuite(TestTrainingFormat))
suite.addTest(requests.makeSuite(TestFilterSchool))
suite.addTest(requests.makeSuite(TestFilterSubjectsInAssessmentsJournal))
suite.addTest(requests.makeSuite(TestFilterGradesInAssessmentsJournal))
suite.addTest(requests.makeSuite(TestFilterUser))
